### ISSUE TITLE
Ablation test on Attention Pert

### ISSUE THREAD

**Issue by HaochenW** [BaiDing1234/AttentionPert#2]
![image](https://github.com/user-attachments/assets/82b8c29f-9bff-4d82-8e80-61bc04a6e8c8)

Hello, I have replicated the Ablation test on your code. I found that without any modifications (original AttentionPert), the best loss for AttentionPert is only around 0.170, and it cannot reach as low as 0.159 (As shown in Table 5 in the paper). I would like to ask if you used the term "test_combo_seen0_mse_top20_de_non_dropout" for an average of five tests? Why can't I achieve a result of 0.159 no matter how I test it?

We want to use this code for some pharmaceutical-related trials, so performance is very important. Do you have any suggestions for us in this regard?

Additionally, the difference after removing the module (For example, when remove PW, 0.1988 compared with 0.246 in Table 5) is not as significant as shown in Table 5. What could be the reason for this?

**Comment by BaiDing1234** [comment]
Hello, thanks for your comment! 
1. Yes we use "test_combo_seen0_mse_top20_de_non_dropout" for the one you said. It is normal for the results to fluctuate like this. As we've shown in the report, the standard deviation of 5 tests is 0.012, with a mean value 0.159, and 0.170 is still inside the 1-sigma deviation. The randomness comes from many places, the biggest possible reason could be the random pairing between unperturbed samples and perturbed samples, which is a method we borrowed from GEARS. A different random pairing can cause a different performance, as we experienced many times. Other reasons may include device differences, random initialization, etc. It is more comprehensive to also take other scores such as the POD, PSD scores, or the Pearson delta scores, of not only 20 DE but also 50, 100 and 200 DE genes. The MSE of the top 20 DE cannot represent everything.
2. it's impossible to have such good results with PW removed. As we tested, PW contributes the most to the whole result and PL contributes only a marginal one (mainly the seen2/2 scenario). Could you please check if you correctly removed the PW, including the weighted effects part and the general effects part? It's not very easy to do as our code is not properly and clearly modulized for the encoders (sorry for that).

**Comment by HaochenW** [comment]
Thank you very much for your quick reply!

1. I understand it. Thank you very much! Indeed, I have tested the model's performance 15 times (5 times * 3) using the default settings given in the README, but the average MSE performance remains at 0.171. I wonder if I need more training iterations or other tricks to improve the performance?
2. I used the ablation string "self.ablation_strings = {"g2v": "Y", "app": "R" , "pl": "Y", "pw": "R"}" in line 103 of https://github.com/BaiDing1234/AttentionPert/blob/main/attnpert/model.py. To remove PW, I used the string {"g2v": "Y", "app": "R" , "pl": "Y", "pw": "N"}, but it may not be sufficient for the ablation. I will check how to properly remove the PW module.

**Comment by BaiDing1234** [comment]
1. No need to conduct more. That's a normal result.
2. Sure, the ablation string is a very early stage code line, that we didn't remove in the final version. We have used another code for a proper ablation study. I will upload the code for ablation if I can still find it.

**Comment by HaochenW** [comment]
Thanks so much for your kind reply! Your answer clearly solve my questions. 
Hope you have a good day!
